# Development environment override
services:
  php:
    build:
      context: .docker
      target: base_symfony_dev
    volumes:
      - ${PWD}/.docker/webserver/conf.d/php.dev.ini:/usr/local/etc/php/php.ini:ro
    environment:
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-debug}"

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###
