# Development environment override
services:
  webserver:
    build:
      context: .docker
      target: base_symfony_dev
    container_name: 'webserver-${CONTAINER_SUFFIX}'
    volumes:
      - ${PWD}/.docker/webserver/conf.d/php.dev.ini:/usr/local/etc/php/php.ini:ro
    environment:
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-debug}"

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "${DB_PORT_EXTERNAL:-5432}:${DB_PORT_INTERNAL:-5432}"
###< doctrine/doctrine-bundle ###
